version: 2
jobs:
  build:
    docker:
      - image: algas/circleci-python-example:latest
    steps:
      - checkout
      - run:
          name: copy
          command: cp /work/hoge ./
      - run:
          name: cat
          command: cat /work/hoge
      - run:
          name: run
          command: python app.py
          background: true
      - run:
          name: test
          command: sleep 5 && curl --retry 10 --retry-delay 5 -v http://localhost:8080
