version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - run:
          name: install dependencies
          command: sudo apt-get install -y curl
      - run:
          name: install dependencies
          command: pip install -r requirements.txt
      - run:
          name: run
          command: python app.py
          background: true
      - run:
          name: test
          command: sleep 5 && curl --retry 10 --retry-delay 5 -v http://localhost:8080
